### ISSUE TITLE
Format (float,double) for type "number" is not taken into account random value generation

### ISSUE THREAD

**Issue by gschafra** [swagger-mock/swagger-mock#6]
**Problem:**
Given a "number" type without a multipleOf attribute but with format "float" or "double" set (see OAS3 spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types) always returns/generates an integer.

**Cause:**
I suppose it's because the format-attribute is not taken into account in the App\Mock\Generation\Value\Primitive\RandomNumberGenerator and App\Mock\Parameters\Schema\Type\Primitive\NumberType.

**Example of a schema:**
```yaml
AnItem:
    value:
          type: number
          format: float
```
